#!/usr/bin/env python3
"""Builder PART 1 of _fundamentals_pit_tests.py. Emits to _eng1.txt.
Uses chr(10).join(list) to dodge the write \\n-injection gotcha."""
L = []
def add(rows):
    L.extend(rows)

add([
'#!/usr/bin/env python3',
'"""FUNDAMENTALS-PIT QUALITY/VALUE cross-sectional composite (candidate research).',
'',
'First genuinely orthogonal-to-OHLCV return engine this bench has tried. Point-in-time',
'fundamentals from SEC EDGAR (filed-date masked, no lookahead), ranked cross-sectionally',
'into a quality+value composite, monthly/quarterly rebalanced long-top-bucket equal-weight,',
'vs buy-and-hold SPY net of 2bps. Long/short spread also reported.',
'',
'HONESTY RAILS: PIT-select on EDGAR filed date (asserted via lookahead canary); ranks from',
'PAST-only data; SPY on the SAME traded path; FULL continuous-span Sharpe; 2bps one-way cost',
'+ breakeven analysis; explicit survivorship-bias disclosure (universe=TODAY S&P100-ish).',
'',
'Candidate/scratch -- touches NO runner/*.py, strategies/*, crontab, *.db, paper clock.',
'"""',
'from __future__ import annotations',
'',
'import bisect',
'import json',
'import math',
'import os',
'import sys',
'import time',
'import urllib.request',
'import urllib.error',
'from datetime import datetime, timezone',
'',
'WS = os.path.dirname(os.path.abspath(__file__))',
'EDGAR_DIR = os.path.join(WS, "data_cache", "edgar_fundamentals")',
'YAHOO = os.path.join(WS, "data_cache", "yahoo", "%s_parsed.json")',
'UA = "trading-bench-research azureuser@example.com"',
'OOS_SPLIT = "2018-12-31"',
'TRADING_DAYS = 252.0',
'os.makedirs(EDGAR_DIR, exist_ok=True)',
'',
'CONCEPTS = [',
'    "NetIncomeLoss", "StockholdersEquity", "Assets", "Liabilities",',
'    "Revenues", "RevenueFromContractWithCustomerExcludingAssessedTax",',
'    "GrossProfit", "AssetsCurrent", "LiabilitiesCurrent",',
'    "CashAndCashEquivalentsAtCarryingValue", "LongTermDebtNoncurrent",',
'    "CostOfRevenue", "CostOfGoodsAndServicesSold",',
']',
'',
'_LAST_FETCH = [0.0]',
'',
'def _throttle(min_spacing=0.13):',
'    dt = time.time() - _LAST_FETCH[0]',
'    if dt < min_spacing:',
'        time.sleep(min_spacing - dt)',
'    _LAST_FETCH[0] = time.time()',
'',
'def fetch_concept(ticker, cik, concept):',
'    safe = ticker.replace("/", "_").replace(".", "_")',
'    cache = os.path.join(EDGAR_DIR, safe + "__" + concept + ".json")',
'    if os.path.exists(cache) and os.path.getsize(cache) >= 2:',
'        try:',
'            return json.load(open(cache))',
'        except Exception:',
'            pass',
'    url = "https://data.sec.gov/api/xbrl/companyconcept/CIK" + cik + "/us-gaap/" + concept + ".json"',
'    req = urllib.request.Request(url, headers={"User-Agent": UA})',
'    facts = []',
'    try:',
'        _throttle()',
'        r = urllib.request.urlopen(req, timeout=40)',
'        raw = r.read().decode("utf-8", "replace")',
'        r.close()',
'        payload = json.loads(raw)',
'        units = payload.get("units", {})',
'        bucket = units.get("USD")',
'        if not bucket:',
'            bucket = units.get("USD/shares")',
'        if not bucket:',
'            for k, v in units.items():',
'                bucket = v',
'                break',
'        facts = bucket or []',
'    except urllib.error.HTTPError as e:',
'        if e.code != 404:',
'            sys.stderr.write("[edgar] " + ticker + " " + concept + " HTTP " + str(e.code) + chr(10))',
'        facts = []',
'    except Exception as e:',
'        sys.stderr.write("[edgar] " + ticker + " " + concept + " ERR " + str(e) + chr(10))',
'        facts = []',
'    try:',
'        json.dump(facts, open(cache, "w"))',
'    except Exception:',
'        pass',
'    return facts',
'',
'def _norm_facts(facts):',
'    rows = []',
'    for f in facts:',
'        filed = f.get("filed"); end = f.get("end"); val = f.get("val")',
'        fy = f.get("fy"); fp = f.get("fp")',
'        if filed and val is not None:',
'            rows.append((filed, end or "", fy or 0, fp or "", float(val)))',
'    rows.sort(key=lambda x: (x[0], x[1]))',
'    return rows',
'',
'def pit_latest(rows, asof):',
'    best = None',
'    for filed, end, fy, fp, val in rows:',
'        if filed <= asof:',
'            if best is None or (filed, end) >= (best[0], best[1]):',
'                best = (filed, end, val)',
'        else:',
'            break',
'    if best is None:',
'        return None',
'    return (best[1], best[2])',
'',
'def _filed_used(rows, asof):',
'    best = None',
'    for filed, end, fy, fp, val in rows:',
'        if filed <= asof:',
'            if best is None or (filed, end) >= (best[0], best[1]):',
'                best = (filed, end, val)',
'        else:',
'            break',
'    return best[0] if best else None',
'',
'def _months_between(a, b):',
'    try:',
'        da = datetime.strptime(a, "%Y-%m-%d"); db = datetime.strptime(b, "%Y-%m-%d")',
'        return abs((db.year - da.year) * 12 + (db.month - da.month))',
'    except Exception:',
'        return 999.0',
'',
'def pit_ttm_flow(rows, asof):',
'    avail = [(f, e, fy, fp, v) for (f, e, fy, fp, v) in rows if f <= asof]',
'    if not avail:',
'        return None',
'    by_end = {}',
'    for f, e, fy, fp, v in avail:',
'        if e not in by_end or f >= by_end[e][0]:',
'            by_end[e] = (f, fy, fp, v)',
'    latest_end = max(by_end.keys())',
'    fy_rows = [(e, vv[0], vv[1], vv[2], vv[3]) for e, vv in by_end.items() if vv[2] == "FY"]',
'    fy_rows.sort(key=lambda x: x[0])',
'    if fy_rows:',
'        fend = fy_rows[-1][0]; fval = fy_rows[-1][4]',
'        if _months_between(fend, latest_end) <= 15:',
'            return fval',
'    q_rows = [(e, vv[3]) for e, vv in by_end.items() if vv[2] in ("Q1", "Q2", "Q3", "Q4")]',
'    q_rows.sort(key=lambda x: x[0])',
'    if len(q_rows) >= 4:',
'        return sum(v for e, v in q_rows[-4:])',
'    return None',
'',
'def load_px(sym):',
'    path = YAHOO % sym',
'    if not os.path.exists(path):',
'        return {}',
'    rows = json.load(open(path))',
'    out = {}',
'    for r in rows:',
'        ac = r.get("adjclose")',
'        if ac not in (None, 0):',
'            out[r["date"]] = float(ac)',
'    return out',
'',
'def load_raw_close(sym):',
'    path = YAHOO % sym',
'    if not os.path.exists(path):',
'        return {}',
'    rows = json.load(open(path))',
'    out = {}',
'    for r in rows:',
'        c = r.get("close")',
'        if c not in (None, 0):',
'            out[r["date"]] = float(c)',
'    return out',
'',
'def asof_price(px, dates_sorted, asof):',
'    i = bisect.bisect_right(dates_sorted, asof) - 1',
'    if i < 0:',
'        return None',
'    return px[dates_sorted[i]]',
'',
'def fetch_shares(ticker, cik):',
'    safe = ticker.replace("/", "_").replace(".", "_")',
'    cache = os.path.join(EDGAR_DIR, safe + "__shares.json")',
'    facts = None',
'    if os.path.exists(cache) and os.path.getsize(cache) >= 2:',
'        try:',
'            facts = json.load(open(cache))',
'        except Exception:',
'            facts = None',
'    if facts is None:',
'        url = ("https://data.sec.gov/api/xbrl/companyconcept/CIK" + cik +',
'               "/dei/EntityCommonStockSharesOutstanding.json")',
'        req = urllib.request.Request(url, headers={"User-Agent": UA})',
'        try:',
'            _throttle()',
'            r = urllib.request.urlopen(req, timeout=40)',
'            raw = r.read().decode("utf-8", "replace")',
'            r.close()',
'            payload = json.loads(raw)',
'            facts = payload.get("units", {}).get("shares", [])',
'        except urllib.error.HTTPError as e:',
'            facts = []',
'        except Exception:',
'            facts = []',
'        try:',
'            json.dump(facts, open(cache, "w"))',
'        except Exception:',
'            pass',
'    rows = []',
'    for f in (facts or []):',
'        filed = f.get("filed"); val = f.get("val")',
'        if filed and val:',
'            rows.append((filed, float(val)))',
'    rows.sort()',
'    return rows',
'',
'def shares_asof(rows, asof):',
'    val = None',
'    for filed, v in rows:',
'        if filed <= asof:',
'            val = v',
'        else:',
'            break',
'    return val',
'',
'def build_fundamentals(univ, verbose=True):',
'    data = {}',
'    n = len(univ)',
'    for i, (tkr, cik) in enumerate(univ.items()):',
'        rec = {}',
'        for concept in CONCEPTS:',
'            rec[concept] = _norm_facts(fetch_concept(tkr, cik, concept))',
'        rec["shares"] = fetch_shares(tkr, cik)',
'        data[tkr] = rec',
'        if verbose and (i % 10 == 0 or i == n - 1):',
'            sys.stderr.write("[fund] " + str(i + 1) + "/" + str(n) + " " + tkr + chr(10))',
'            sys.stderr.flush()',
'    return data',
'',
])

src = chr(10).join(L) + chr(10)
open('_eng1.txt', 'w').write(src)
print("part1:", len(L), "lines,", len(src), "bytes -> _eng1.txt")
