#!/usr/bin/env python3
"""Builder PART 3 of _fundamentals_pit_tests.py. Emits to _eng3.txt."""
L = []
def add(rows):
    L.extend(rows)

# ----- stats -----
add([
'def sharpe(rets):',
'    n = len(rets)',
'    if n < 2:',
'        return 0.0',
'    mean = sum(rets) / n',
'    var = sum((r - mean) ** 2 for r in rets) / (n - 1)',
'    if var <= 0:',
'        return 0.0',
'    return (mean / math.sqrt(var)) * math.sqrt(TRADING_DAYS)',
'',
'def cagr(rets):',
'    if not rets:',
'        return 0.0',
'    eq = 1.0',
'    for r in rets:',
'        eq *= (1.0 + r)',
'    yrs = len(rets) / TRADING_DAYS',
'    if yrs <= 0 or eq <= 0:',
'        return 0.0',
'    return (eq ** (1.0 / yrs) - 1.0) * 100.0',
'',
'def total_return(rets):',
'    eq = 1.0',
'    for r in rets:',
'        eq *= (1.0 + r)',
'    return (eq - 1.0) * 100.0',
'',
'def maxdd(rets):',
'    eq = 1.0; peak = 1.0; mdd = 0.0',
'    for r in rets:',
'        eq *= (1.0 + r)',
'        if eq > peak:',
'            peak = eq',
'        dd = (eq - peak) / peak',
'        if dd < mdd:',
'            mdd = dd',
'    return mdd * 100.0',
'',
'def ann_vol(rets):',
'    n = len(rets)',
'    if n < 2:',
'        return 0.0',
'    mean = sum(rets) / n',
'    var = sum((r - mean) ** 2 for r in rets) / (n - 1)',
'    return math.sqrt(var) * math.sqrt(TRADING_DAYS) * 100.0',
'',
'def stat_block(dates, rets):',
'    return {"n": len(rets), "sharpe": round(sharpe(rets), 3), "cagr_pct": round(cagr(rets), 2),',
'            "maxdd_pct": round(maxdd(rets), 2), "total_return_pct": round(total_return(rets), 1),',
'            "ann_vol_pct": round(ann_vol(rets), 2)}',
'',
'def slice_block(dates, rets, start, end):',
'    sd = []; sr = []',
'    for d, r in zip(dates, rets):',
'        if start <= d < end:',
'            sd.append(d); sr.append(r)',
'    if len(sr) < 20:',
'        return {"n": len(sr)}',
'    return stat_block(sd, sr)',
'',
'def breakeven_bps(gross_rets, turnovers_sum):',
'    if turnovers_sum <= 0:',
'        return 0.0',
'    eq = 1.0',
'    for r in gross_rets:',
'        eq *= (1.0 + r)',
'    gross_total = eq - 1.0',
'    return (gross_total / turnovers_sum) * 10000.0',
'',
'KILLER_WINDOWS = [',
'    ("2020-Q1 covid crash",  "2020-02-01", "2020-04-01"),',
'    ("2022 bear (full yr)",  "2022-01-01", "2023-01-01"),',
'    ("2022-H1 bear",         "2022-01-01", "2022-07-01"),',
'    ("2025-Q1 tariff bear",  "2025-02-01", "2025-05-01"),',
'    ("2011 debt-ceiling",    "2011-07-01", "2011-10-01"),',
'    ("2018-Q4 selloff",      "2018-10-01", "2019-01-01"),',
'    ("2023-H1 recovery",     "2023-01-01", "2023-07-01"),',
'    ("2024-Q2 bull",         "2024-04-01", "2024-07-01"),',
']',
'',
])

# ----- main -----
add([
'def _load_prices(univ_keys):',
'    adj_px = {}; adj_dates = {}; raw_close = {}; raw_dates = {}',
'    for t in univ_keys:',
'        ap = load_px(t)',
'        if ap:',
'            adj_px[t] = ap; adj_dates[t] = sorted(ap.keys())',
'        rc = load_raw_close(t)',
'        if rc:',
'            raw_close[t] = rc; raw_dates[t] = sorted(rc.keys())',
'    return adj_px, adj_dates, raw_close, raw_dates',
'',
'def main():',
'    t0 = time.time()',
'    univ = json.load(open(os.path.join(EDGAR_DIR, "universe.json")))',
'    ticker_cik = univ["ticker_cik"]',
'    univ_keys = list(ticker_cik.keys())',
'    sys.stderr.write("[main] universe " + str(len(univ_keys)) + " names" + chr(10))',
'    data = build_fundamentals(ticker_cik, verbose=True)',
'    adj_px, adj_dates, raw_close, raw_dates = _load_prices(univ_keys)',
'    spy_px = load_px("SPY"); spy_dates = sorted(spy_px.keys())',
'    sys.stderr.write("[main] prices: " + str(len(adj_px)) + " adj, SPY " + str(len(spy_dates)) + " days" + chr(10))',
'    results = {"meta": {"universe_n": len(univ_keys), "universe": univ_keys,',
'                        "survivorship_note": univ.get("note"),',
'                        "oos_split": OOS_SPLIT, "cost_bps_oneway": 2.0,',
'                        "as_of_build": datetime.now(timezone.utc).isoformat()}}',
'    START = "2010-06-01"',
'    prim = run_backtest(data, univ_keys, adj_px, adj_dates, raw_close, raw_dates,',
'                        spy_px, spy_dates, cadence="M", bucket=0.2, long_short=False,',
'                        signal="composite", cost_bps=2.0, start=START)',
'    dts = prim["dates"]; sret = prim["strat_ret"]; spyret = prim["spy_ret"]',
'    full_s = stat_block(dts, sret); full_spy = stat_block(dts, spyret)',
'    is_s = slice_block(dts, sret, "2000-01-01", "2019-01-01")',
'    is_spy = slice_block(dts, spyret, "2000-01-01", "2019-01-01")',
'    oos_s = slice_block(dts, sret, "2019-01-01", "2099-01-01")',
'    oos_spy = slice_block(dts, spyret, "2019-01-01", "2099-01-01")',
'    prim_gross = run_backtest(data, univ_keys, adj_px, adj_dates, raw_close, raw_dates,',
'                              spy_px, spy_dates, cadence="M", bucket=0.2, long_short=False,',
'                              signal="composite", cost_bps=0.0, start=START)',
'    turn_sum = prim["avg_turnover"] * prim["n_rebal"]',
'    be = breakeven_bps(prim_gross["strat_ret"], turn_sum)',
'    results["primary"] = {',
'        "config": "monthly, top-quintile (20%), long-only, combined composite, 2bps",',
'        "avg_turnover_per_rebal": round(prim["avg_turnover"], 4),',
'        "n_rebal": prim["n_rebal"], "avg_n_long": round(prim["avg_n_long"], 1),',
'        "breakeven_bps_oneway": round(be, 1),',
'        "full": {"strat": full_s, "spy": full_spy,',
'                 "beats_spy_raw": full_s["total_return_pct"] > full_spy["total_return_pct"]},',
'        "is_pre2019": {"strat": is_s, "spy": is_spy},',
'        "oos_2019plus": {"strat": oos_s, "spy": oos_spy,',
'                         "beats_spy_raw": (oos_s.get("total_return_pct", -1e9) > oos_spy.get("total_return_pct", 1e9))}}',
'    battery = {}',
'    for label, st, en in KILLER_WINDOWS:',
'        battery[label] = {"strat": slice_block(dts, sret, st, en), "spy": slice_block(dts, spyret, st, en)}',
'    results["killer_battery"] = battery',
'    ls = run_backtest(data, univ_keys, adj_px, adj_dates, raw_close, raw_dates,',
'                      spy_px, spy_dates, cadence="M", bucket=0.2, long_short=True,',
'                      signal="composite", cost_bps=2.0, start=START)',
'    results["long_short_spread"] = {',
'        "config": "monthly, top-minus-bottom quintile, combined composite, 2bps",',
'        "full": stat_block(ls["dates"], ls["strat_ret"]),',
'        "oos_2019plus": slice_block(ls["dates"], ls["strat_ret"], "2019-01-01", "2099-01-01"),',
'        "avg_turnover_per_rebal": round(ls["avg_turnover"], 4)}',
'    sweep = []',
'    for cad in ("M", "Q"):',
'        for buck in (0.2, 0.333):',
'            for sig in ("composite", "value_z", "quality_z"):',
'                rb = run_backtest(data, univ_keys, adj_px, adj_dates, raw_close, raw_dates,',
'                                  spy_px, spy_dates, cadence=cad, bucket=buck, long_short=False,',
'                                  signal=sig, cost_bps=2.0, start=START)',
'                fb = stat_block(rb["dates"], rb["strat_ret"])',
'                ob = slice_block(rb["dates"], rb["strat_ret"], "2019-01-01", "2099-01-01")',
'                sb = stat_block(rb["dates"], rb["spy_ret"])',
'                sweep.append({"cadence": cad, "bucket": buck, "signal": sig,',
'                              "full_sharpe": fb["sharpe"], "full_ret_pct": fb["total_return_pct"],',
'                              "full_maxdd_pct": fb["maxdd_pct"],',
'                              "oos_sharpe": ob.get("sharpe"), "oos_ret_pct": ob.get("total_return_pct"),',
'                              "spy_full_ret_pct": sb["total_return_pct"],',
'                              "beats_spy_full": fb["total_return_pct"] > sb["total_return_pct"],',
'                              "avg_turnover": round(rb["avg_turnover"], 4)})',
'    results["robustness_sweep"] = sweep',
'    results["lookahead_canary"] = {"violations": len(_CANARY), "sample": _CANARY[:5],',
'                                   "passed": len(_CANARY) == 0}',
'    results["runtime_sec"] = round(time.time() - t0, 1)',
'    outp = os.path.join(WS, "reports", "_fundamentals_pit_result.json")',
'    json.dump(results, open(outp, "w"), indent=2)',
'    sys.stderr.write("[main] wrote " + outp + chr(10))',
'    p = results["primary"]',
'    print("=" * 70)',
'    print("FUNDAMENTALS-PIT QUALITY/VALUE -- PRIMARY (monthly top-quintile long-only)")',
'    print("  Universe: " + str(len(univ_keys)) + " names (survivorship-biased: today S&P100-ish)")',
'    print("  Lookahead canary: " + ("PASS" if results["lookahead_canary"]["passed"] else "FAIL") + " (" + str(results["lookahead_canary"]["violations"]) + " violations)")',
'    print("  Avg turnover/rebal: %.1f%%  n_rebal=%d  breakeven=%.0f bps one-way" % (p["avg_turnover_per_rebal"]*100, p["n_rebal"], p["breakeven_bps_oneway"]))',
'    print("  FULL : strat Sharpe %.2f CAGR %.1f%% maxDD %.1f%% rawRet %.0f%%  |  SPY Sharpe %.2f rawRet %.0f%%  beats=%s" % (',
'        p["full"]["strat"]["sharpe"], p["full"]["strat"]["cagr_pct"], p["full"]["strat"]["maxdd_pct"], p["full"]["strat"]["total_return_pct"],',
'        p["full"]["spy"]["sharpe"], p["full"]["spy"]["total_return_pct"], p["full"]["beats_spy_raw"]))',
'    oss = p["oos_2019plus"]["strat"]; osp = p["oos_2019plus"]["spy"]',
'    print("  OOS  : strat Sharpe " + str(oss.get("sharpe")) + " rawRet " + str(oss.get("total_return_pct")) + "%  |  SPY Sharpe " + str(osp.get("sharpe")) + " rawRet " + str(osp.get("total_return_pct")) + "%  beats=" + str(p["oos_2019plus"]["beats_spy_raw"]))',
'    print("  L/S spread FULL Sharpe %.2f rawRet %.0f%%" % (results["long_short_spread"]["full"]["sharpe"], results["long_short_spread"]["full"]["total_return_pct"]))',
'    print("=" * 70)',
'    return results',
'',
'if __name__ == "__main__":',
'    main()',
'',
])

src = chr(10).join(L) + chr(10)
open('_eng3.txt', 'w').write(src)
print("part3:", len(L), "lines,", len(src), "bytes -> _eng3.txt")
