#!/usr/bin/env python3
"""Builder PART 2 of _fundamentals_pit_tests.py. Emits to _eng2.txt."""
L = []
def add(rows):
    L.extend(rows)

# ----- PIT snapshot + canary -----
add([
'_CANARY = []',
'',
'def pit_snapshot(rec, asof):',
'    out = {"max_filed": None}',
'    def stock(concept):',
'        rows = rec.get(concept, [])',
'        r = pit_latest(rows, asof)',
'        f = _filed_used(rows, asof)',
'        if f is not None:',
'            if out["max_filed"] is None or f > out["max_filed"]:',
'                out["max_filed"] = f',
'            if f > asof:',
'                _CANARY.append((concept, f, asof))',
'        return r[1] if r else None',
'    def flow(concept):',
'        rows = rec.get(concept, [])',
'        v = pit_ttm_flow(rows, asof)',
'        f = _filed_used(rows, asof)',
'        if f is not None:',
'            if out["max_filed"] is None or f > out["max_filed"]:',
'                out["max_filed"] = f',
'            if f > asof:',
'                _CANARY.append((concept, f, asof))',
'        return v',
'    out["equity"] = stock("StockholdersEquity")',
'    out["assets"] = stock("Assets")',
'    out["liabilities"] = stock("Liabilities")',
'    out["cash"] = stock("CashAndCashEquivalentsAtCarryingValue")',
'    out["ltd"] = stock("LongTermDebtNoncurrent")',
'    out["ni_ttm"] = flow("NetIncomeLoss")',
'    rev = flow("Revenues")',
'    if rev is None:',
'        rev = flow("RevenueFromContractWithCustomerExcludingAssessedTax")',
'    out["rev_ttm"] = rev',
'    out["gross_profit_ttm"] = flow("GrossProfit")',
'    cogs = flow("CostOfRevenue")',
'    if cogs is None:',
'        cogs = flow("CostOfGoodsAndServicesSold")',
'    out["cogs_ttm"] = cogs',
'    return out',
'',
'def noa_from_snap(s):',
'    a = s.get("assets"); cash = s.get("cash"); liab = s.get("liabilities"); ltd = s.get("ltd")',
'    if a is None:',
'        return None',
'    op_assets = a - (cash or 0.0)',
'    op_liab = liab',
'    if op_liab is None:',
'        eq = s.get("equity")',
'        if eq is not None:',
'            op_liab = a - eq',
'        else:',
'            return None',
'    op_liab = op_liab - (ltd or 0.0)',
'    return op_assets - op_liab',
'',
'def _yago(asof):',
'    y, m, d = asof.split("-")',
'    return "%04d-%s-%s" % (int(y) - 1, m, d)',
'',
])

# ----- factors / composite -----
add([
'def _median(xs):',
'    s = sorted(xs); n = len(s)',
'    if n == 0:',
'        return 0.0',
'    return s[n // 2] if n % 2 else 0.5 * (s[n // 2 - 1] + s[n // 2])',
'',
'def _zscores(vals):',
'    items = []',
'    for k, v in vals.items():',
'        if v is None:',
'            continue',
'        if isinstance(v, float) and (math.isnan(v) or math.isinf(v)):',
'            continue',
'        items.append((k, v))',
'    if len(items) < 5:',
'        return {}',
'    xs = [v for _, v in items]',
'    med = _median(xs)',
'    mad = _median([abs(v - med) for v in xs]) or 1e-9',
'    sd = 1.4826 * mad',
'    out = {}',
'    for k, v in items:',
'        z = (v - med) / sd',
'        if z > 3:',
'            z = 3.0',
'        if z < -3:',
'            z = -3.0',
'        out[k] = z',
'    return out',
'',
'def compute_factors(data, univ_keys, asof, raw_close, px_dates):',
'    snaps = {}; noa_now = {}; noa_prev = {}; mktcap = {}',
'    yago = _yago(asof)',
'    for t in univ_keys:',
'        rec = data.get(t)',
'        if not rec:',
'            continue',
'        s = pit_snapshot(rec, asof)',
'        snaps[t] = s',
'        sh = shares_asof(rec.get("shares", []), asof)',
'        rc = raw_close.get(t, {}); rcd = px_dates.get(t, [])',
'        price = asof_price(rc, rcd, asof)',
'        if sh and price and sh > 0 and price > 0:',
'            mktcap[t] = sh * price',
'        noa_now[t] = noa_from_snap(s)',
'        noa_prev[t] = noa_from_snap(pit_snapshot(rec, yago))',
'    ep = {}; bp = {}; roe = {}; roa = {}; gprof = {}; lowlev = {}; lowacc = {}',
'    for t, s in snaps.items():',
'        mc = mktcap.get(t)',
'        ni = s.get("ni_ttm"); eq = s.get("equity"); a = s.get("assets")',
'        if mc and ni is not None:',
'            ep[t] = ni / mc',
'        if mc and eq is not None and eq > 0:',
'            bp[t] = eq / mc',
'        if ni is not None and eq and eq > 0:',
'            roe[t] = ni / eq',
'        if ni is not None and a and a > 0:',
'            roa[t] = ni / a',
'        gp = s.get("gross_profit_ttm")',
'        if gp is None:',
'            rev = s.get("rev_ttm"); cogs = s.get("cogs_ttm")',
'            if rev is not None and cogs is not None:',
'                gp = rev - cogs',
'        if gp is not None and a and a > 0:',
'            gprof[t] = gp / a',
'        if eq is not None and a and a > 0:',
'            lowlev[t] = eq / a',
'        nn = noa_now.get(t); npv = noa_prev.get(t)',
'        if nn is not None and npv is not None and a and a > 0:',
'            lowacc[t] = -((nn - npv) / a)',
'    z_ep = _zscores(ep); z_bp = _zscores(bp)',
'    z_roe = _zscores(roe); z_roa = _zscores(roa); z_gp = _zscores(gprof)',
'    z_lev = _zscores(lowlev); z_acc = _zscores(lowacc)',
'    out = {}',
'    for t in snaps:',
'        vparts = [z for z in (z_ep.get(t), z_bp.get(t)) if z is not None]',
'        qparts = [z for z in (z_roe.get(t), z_roa.get(t), z_gp.get(t), z_lev.get(t), z_acc.get(t)) if z is not None]',
'        if not vparts and not qparts:',
'            continue',
'        vz = sum(vparts) / len(vparts) if vparts else None',
'        qz = sum(qparts) / len(qparts) if qparts else None',
'        cp = [x for x in (vz, qz) if x is not None]',
'        comp = sum(cp) / len(cp) if cp else None',
'        if comp is None:',
'            continue',
'        out[t] = {"composite": comp, "value_z": vz if vz is not None else 0.0,',
'                  "quality_z": qz if qz is not None else 0.0,',
'                  "n_value": len(vparts), "n_quality": len(qparts)}',
'    return out',
'',
])

# ----- backtest engine -----
add([
'def month_starts(dates):',
'    seen = set(); idx = []',
'    for i, d in enumerate(dates):',
'        ym = d[:7]',
'        if ym not in seen:',
'            seen.add(ym); idx.append(i)',
'    return idx',
'',
'def quarter_starts(dates):',
'    seen = set(); idx = []',
'    for i, d in enumerate(dates):',
'        y = d[:4]; m = int(d[5:7]); q = (m - 1) // 3 + 1',
'        if (y, q) not in seen:',
'            seen.add((y, q)); idx.append(i)',
'    return idx',
'',
'def _bucket_ret(names, adj_px, d_prev, d_now):',
'    if not names:',
'        return 0.0',
'    rs = []',
'    for t in names:',
'        px = adj_px.get(t, {})',
'        p0 = px.get(d_prev); p1 = px.get(d_now)',
'        if p0 and p1 and p0 > 0:',
'            rs.append(p1 / p0 - 1.0)',
'    if not rs:',
'        return 0.0',
'    return sum(rs) / len(rs)',
'',
'def run_backtest(data, univ_keys, adj_px, adj_dates, raw_close, raw_dates,',
'                 spy_px, spy_dates, cadence="M", bucket=0.2, long_short=False,',
'                 signal="composite", cost_bps=2.0, start="2010-06-01"):',
'    cal = [d for d in spy_dates if d >= start]',
'    if not cal:',
'        return None',
'    rb_idx = month_starts(cal) if cadence == "M" else quarter_starts(cal)',
'    rb_set = set(rb_idx)',
'    spy_ret = [0.0]',
'    for i in range(1, len(cal)):',
'        p0 = spy_px.get(cal[i - 1]); p1 = spy_px.get(cal[i])',
'        spy_ret.append((p1 / p0 - 1.0) if (p0 and p1 and p0 > 0) else 0.0)',
'    cur_long = []; cur_short = []',
'    strat_ret = [0.0]',
'    turnovers = []; rebal_log = []; prev_set = set(); n_names_log = []',
'    for i in range(len(cal)):',
'        d = cal[i]',
'        if i in rb_set:',
'            fac = compute_factors(data, univ_keys, d, raw_close, raw_dates)',
'            ranked = sorted(fac.items(), key=lambda kv: kv[1][signal], reverse=True)',
'            m = len(ranked)',
'            if m >= 10:',
'                k = max(1, int(round(m * bucket)))',
'                top = [t for t, _ in ranked[:k]]',
'                bot = [t for t, _ in ranked[-k:]] if long_short else []',
'                new_set = set(top) | set("S__" + x for x in bot)',
'                if prev_set:',
'                    changed = len(new_set.symmetric_difference(prev_set))',
'                    denom = max(1, len(new_set) + len(prev_set))',
'                    turn = changed / denom',
'                else:',
'                    turn = 1.0',
'                turnovers.append(turn)',
'                cur_long = top; cur_short = bot; prev_set = new_set',
'                n_names_log.append(len(top))',
'                cost = (cost_bps / 10000.0) * turn',
'                strat_ret[-1] = strat_ret[-1] - cost',
'                rebal_log.append({"date": d, "n_long": len(top), "n_short": len(bot), "turnover": turn})',
'        if i == 0:',
'            continue',
'        rl = _bucket_ret(cur_long, adj_px, cal[i - 1], d)',
'        if long_short and cur_short:',
'            rs = _bucket_ret(cur_short, adj_px, cal[i - 1], d)',
'            day = rl - rs',
'        else:',
'            day = rl',
'        strat_ret.append(day)',
'    avg_turn = sum(turnovers) / len(turnovers) if turnovers else 0.0',
'    return {"dates": cal, "strat_ret": strat_ret, "spy_ret": spy_ret,',
'            "avg_turnover": avg_turn, "n_rebal": len(turnovers),',
'            "rebal_log": rebal_log,',
'            "avg_n_long": (sum(n_names_log) / len(n_names_log) if n_names_log else 0)}',
'',
])

src = chr(10).join(L) + chr(10)
open('_eng2.txt', 'w').write(src)
print("part2:", len(L), "lines,", len(src), "bytes -> _eng2.txt")
