#!/usr/bin/env python3
"""cover_letter_pdf.py — generate a tailored cover-letter PDF for ATS forms
that REQUIRE a cover-letter FILE upload (no text-area alternative).

Motivation (chain_044, Forbes 1399, 2026-06-02): some Greenhouse boards make
the Cover Letter a required FILE input (`#cover_letter`) with no text fallback.
The submit runners had no way to produce + attach such a file, so those roles
hard-blocked even though the rest of the form filled cleanly.

This module:
  1. Builds a tailored cover-letter BODY via the same LLM path the essay
     generator uses (`model_config.model_run_cmd`, inherits the agent model).
  2. Renders it to a clean 1-page PDF via LibreOffice headless — the SAME
     toolchain `tailor_resume.convert_to_pdf` uses (python-docx -> soffice).
  3. Returns the PDF path so a runner can upload it to `#cover_letter`
     mirroring the resume DataTransfer / S3 path.

Truthfulness contract (mirrors cover_answer_generator + MEMORY doctrine
2026-05-31): biographical facts (employer/title/dates/education/metrics) stay
TRUTHFUL and are sourced from personal-info.json + the resume; motivational /
"why this company" framing MAY assert inferred company-specific enthusiasm as
Cyrus's own. No AI/LLM-disclosure leaks. No fabricated employers or metrics.

CLI:
  python cover_letter_pdf.py --company "Forbes" --role "Product Manager" \
      --jd-file applications/dryrun/forbes-5826489004.json \
      --out applications/queued/forbes-5826489004/Cyrus_Shekari_CoverLetter.pdf

  # or resolve everything from a packet slug:
  python cover_letter_pdf.py --slug forbes-5826489004

Returns JSON on stdout: {"pdf": "<path>", "docx": "<path>", "chars": N}
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
PROJECT = HERE.parent
sys.path.insert(0, str(HERE))

from model_config import model_run_cmd  # noqa: E402

PERSONAL_INFO = PROJECT / "personal-info.json"
QUEUED_DIR = PROJECT / "applications" / "queued"
SUBMITTED_DIR = PROJECT / "applications" / "submitted"
DRYRUN_DIR = PROJECT / "applications" / "dryrun"

# Reuse the resume PDF toolchain so output looks consistent + headless-safe.
sys.path.insert(0, str(HERE))
import tailor_resume as _tr  # noqa: E402

# AI-disclosure leak guard (same banned set as cover_answer_generator).
_BANNED_RE = re.compile(
    r"\b(as an ai|language model|chatgpt|\bgpt\b|claude|openai|"
    r"i am an ai|generated by|large language model|\bllm\b)\b", re.I)

MAX_BODY_CHARS = 2200  # ~3 short paragraphs; keeps it to a single clean page.


# --------------------------------------------------------------------------- #
# packet / input resolution
# --------------------------------------------------------------------------- #
def resolve_packet_dir(slug: str) -> Path | None:
    for base in (QUEUED_DIR, SUBMITTED_DIR):
        p = base / slug
        if p.is_dir():
            return p
    return None


def load_jd_text(jd_file: Path | None, slug: str | None) -> str:
    """Best-effort JD text from a dryrun spec json or packet."""
    candidates: list[Path] = []
    if jd_file:
        candidates.append(jd_file)
    if slug:
        candidates += [DRYRUN_DIR / f"{slug}.json"]
        pkt = resolve_packet_dir(slug)
        if pkt:
            candidates += [pkt / "jd.txt", pkt / "jd.json", pkt / "spec.json"]
    for c in candidates:
        if c and c.exists():
            txt = c.read_text(errors="ignore")
            if c.suffix == ".json":
                try:
                    obj = json.loads(txt)
                    for k in ("jd_text", "description", "content", "jd"):
                        if isinstance(obj.get(k), str) and obj[k].strip():
                            return obj[k]
                    # fall back to whole-json string
                    return json.dumps(obj)[:8000]
                except Exception:
                    return txt[:8000]
            return txt[:8000]
    return ""


def load_resume_text() -> str:
    rt = PROJECT / "resume" / "Cyrus_Shekari_Resume.txt"
    return rt.read_text(errors="ignore") if rt.exists() else ""


# --------------------------------------------------------------------------- #
# generation
# --------------------------------------------------------------------------- #
def build_prompt(company: str, role: str, jd_text: str, resume_text: str,
                 personal_info: dict) -> str:
    pi = json.dumps({
        "identity": personal_info.get("identity"),
        "experience_summary": personal_info.get("experience_summary"),
        "education": personal_info.get("education"),
        "preferences": personal_info.get("preferences"),
    }, indent=2)
    return f"""You are writing a cover letter for a job application on behalf of the candidate below. Output ONLY the cover-letter BODY text (no header block, no "Dear Hiring Manager" salutation, no sign-off name line — those are added by the renderer). 3 short paragraphs, professional, confident, specific. Under {MAX_BODY_CHARS} characters.

HARD RULES:
- Biographical facts MUST be truthful and come ONLY from the resume / candidate info below (employer, title, dates, education, metrics). Do NOT invent employers, titles, projects, numbers, or credentials.
- You MAY express specific, inferred enthusiasm for {company} and connect the candidate's real experience to {role}. Motivational framing is allowed; fabricated facts are not.
- NEVER mention AI, language models, that this was generated, or any tool. Write as the candidate.
- No placeholders like [Company] or [X years] — use concrete values or omit.

CANDIDATE INFO:
{pi}

RESUME (source of truth for all factual claims):
{resume_text[:4000]}

TARGET COMPANY: {company}
TARGET ROLE: {role}

JOB DESCRIPTION (for tailoring; do not copy verbatim):
{jd_text[:4000]}

Return ONLY the body paragraphs as plain text."""


def call_model(prompt: str, timeout: int = 300) -> str:
    cmd = model_run_cmd(prompt)
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
    if proc.returncode != 0:
        raise RuntimeError(f"model call failed rc={proc.returncode}: {proc.stderr[:500]}")
    out = proc.stdout.strip()
    # model_run_cmd returns JSON by default; extract the text field if so.
    try:
        obj = json.loads(out)
        # OpenClaw model.run envelope: {"ok":true,...,"outputs":[{"text":...}]}
        # (this is the shape model_run_cmd actually returns; without handling it
        # the whole JSON — including "model":"claude-..." — leaked into the body
        # and tripped the AI-disclosure guard. 2026-06-02 gh-coverletter.)
        outs = obj.get("outputs")
        if isinstance(outs, list) and outs:
            t = outs[0].get("text") if isinstance(outs[0], dict) else None
            if isinstance(t, str) and t.strip():
                return t.strip()
        for k in ("text", "output", "content", "result"):
            if isinstance(obj.get(k), str):
                return obj[k].strip()
        # some shapes nest under message/choices
        if isinstance(obj.get("message"), dict):
            c = obj["message"].get("content")
            if isinstance(c, str):
                return c.strip()
    except Exception:
        pass
    return out


def sanitize_body(body: str) -> str:
    body = body.strip()
    # strip any accidental salutation/signoff the model added
    body = re.sub(r"^(dear[^\n]*\n)", "", body, flags=re.I)
    body = re.sub(r"\n+(sincerely|regards|best|thank you)[,]?\s*\n.*$", "",
                  body, flags=re.I | re.S)
    if len(body) > MAX_BODY_CHARS:
        # trim on a paragraph boundary
        cut = body[:MAX_BODY_CHARS]
        body = cut.rsplit("\n\n", 1)[0] if "\n\n" in cut else cut
    return body.strip()


def validate(body: str) -> list[str]:
    errs = []
    if not body or len(body) < 200:
        errs.append("body too short / empty")
    if _BANNED_RE.search(body):
        errs.append("AI-disclosure leak in body")
    if re.search(r"\[[A-Za-z ]+\]", body):
        errs.append("unfilled placeholder bracket present")
    return errs


# --------------------------------------------------------------------------- #
# render to PDF (docx -> soffice, identical toolchain to resume)
# --------------------------------------------------------------------------- #
def render_pdf(body: str, company: str, role: str, personal_info: dict,
               out_pdf: Path) -> tuple[Path, Path]:
    from docx import Document  # type: ignore
    from docx.shared import Pt, Inches  # type: ignore

    ident = personal_info.get("identity", {}) or {}
    contact = personal_info.get("contact", {}) or {}
    name = ident.get("full_name") or ident.get("name") or (ident.get("first_name", "") + " " + ident.get("last_name", "")).strip() or ""
    email = contact.get("email", "")
    phone = contact.get("phone", "")
    loc = (personal_info.get("address", {}) or {}).get("city_state") or "Kirkland, WA"

    doc = Document()
    for section in doc.sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1)
        section.right_margin = Inches(1)
    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(11)

    def para(text="", bold=False, size=11, after=6):
        p = doc.add_paragraph()
        p.paragraph_format.space_after = Pt(after)
        p.paragraph_format.space_before = Pt(0)
        if text:
            r = p.add_run(text)
            r.bold = bold
            r.font.size = Pt(size)
        return p

    # header
    para(name, bold=True, size=14, after=2)
    contact_line = "  |  ".join([x for x in (loc, email, phone) if x])
    if contact_line:
        para(contact_line, size=10, after=12)
    # salutation
    para(f"Dear {company} Hiring Team,", after=10)
    # body paragraphs
    for blk in [b for b in re.split(r"\n\s*\n", body) if b.strip()]:
        para(blk.strip().replace("\n", " "), after=10)
    # signoff
    para("Sincerely,", after=2)
    para(name)

    out_pdf.parent.mkdir(parents=True, exist_ok=True)
    docx_path = out_pdf.with_suffix(".docx")
    doc.save(str(docx_path))
    _tr.convert_to_pdf(docx_path, out_pdf)
    return out_pdf, docx_path


# --------------------------------------------------------------------------- #
# orchestration
# --------------------------------------------------------------------------- #
def generate(company: str, role: str, *, jd_file: Path | None = None,
             slug: str | None = None, out_pdf: Path | None = None,
             max_retries: int = 2) -> dict:
    personal_info = json.loads(PERSONAL_INFO.read_text())
    jd_text = load_jd_text(jd_file, slug)
    resume_text = load_resume_text()

    body = ""
    last_errs: list[str] = []
    for attempt in range(max_retries + 1):
        prompt = build_prompt(company, role, jd_text, resume_text, personal_info)
        if last_errs:
            prompt += ("\n\nYOUR PREVIOUS DRAFT FAILED VALIDATION: "
                       + "; ".join(last_errs) + ". Fix and rewrite.")
        raw = call_model(prompt)
        body = sanitize_body(raw)
        last_errs = validate(body)
        if not last_errs:
            break
    if last_errs:
        raise RuntimeError(f"cover letter failed validation after retries: {last_errs}")

    if out_pdf is None:
        safe = re.sub(r"[^a-z0-9]+", "", company.lower())
        base = resolve_packet_dir(slug) if slug else (QUEUED_DIR / (slug or safe))
        base = base or (QUEUED_DIR / (slug or safe))
        out_pdf = base / f"Cyrus_Shekari_CoverLetter_{safe}.pdf"

    pdf, docx = render_pdf(body, company, role, personal_info, out_pdf)
    return {"pdf": str(pdf), "docx": str(docx), "chars": len(body)}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--company")
    ap.add_argument("--role", default="")
    ap.add_argument("--jd-file")
    ap.add_argument("--slug")
    ap.add_argument("--out")
    args = ap.parse_args()

    company = args.company
    role = args.role
    if args.slug and not company:
        # derive company from dryrun spec if not given
        spec = DRYRUN_DIR / f"{args.slug}.json"
        if spec.exists():
            try:
                obj = json.loads(spec.read_text())
                company = company or obj.get("company") or args.slug.split("-")[0].title()
                role = role or obj.get("title") or obj.get("role") or ""
            except Exception:
                company = company or args.slug.split("-")[0].title()
    if not company:
        print(json.dumps({"error": "company required (or resolvable from --slug)"}))
        return 2

    res = generate(
        company, role,
        jd_file=Path(args.jd_file) if args.jd_file else None,
        slug=args.slug,
        out_pdf=Path(args.out) if args.out else None,
    )
    print(json.dumps(res))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
