#!/usr/bin/env python3
"""prd_brief_pdf.py — generate a sanitized PRD / product-brief PDF for ATS
forms that REQUIRE a custom "attach a PRD / product brief / writing sample"
FILE upload (no text-area alternative).

Motivation (ACLU 2660/2661/2662, 2026-06-10): some Greenhouse PM roles add a
required custom FILE question like:
  "Please attach a PRD or product brief for a product you've launched before.
   Please make sure to redact any sensitive details."
There is no resume/cover-letter input that satisfies it, so the form
hard-blocks even though everything else fills cleanly. The submit runner had
no way to PRODUCE such an artifact.

This module mirrors cover_letter_pdf.py:
  1. Builds a structured product-brief BODY via the same LLM path the cover
     letter / essay generators use (model_config.model_run_cmd, inherits the
     agent model).
  2. Renders it to a clean, multi-section PDF (title + headed sections) via
     python-docx -> LibreOffice headless (tailor_resume.convert_to_pdf).
  3. Returns the PDF path so a runner can set_input_files() it onto the
     required custom file input.

Truthfulness / sanitization contract:
  - Grounded ONLY in Cyrus's real resume experience (the Microsoft 0->1
    "Resilience Automation Platform" he defined product requirements for).
  - It is a REDACTED / generic brief: no confidential customer names beyond
    what already ships on the public resume, no internal metrics that are not
    on the resume, no proprietary detail. This directly satisfies the form's
    own "please redact any sensitive details" instruction.
  - No AI/LLM-disclosure leaks (same banned set as cover_answer_generator).

CLI:
  python prd_brief_pdf.py --company "ACLU" --role "Product Manager II, CRM" \
      --jd-file applications/dryrun/aclu-8220646002.json \
      --out /tmp/openclaw/uploads/Cyrus_Shekari_PRD_aclu.pdf

Returns JSON on stdout: {"pdf": "<path>", "docx": "<path>", "chars": N}
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
PROJECT = HERE.parent
sys.path.insert(0, str(HERE))

from model_config import model_run_cmd  # noqa: E402
import subprocess  # noqa: E402

PERSONAL_INFO = PROJECT / "personal-info.json"
RESUME_TXT = PROJECT / "resume" / "Cyrus_Shekari_Resume.txt"

import tailor_resume as _tr  # noqa: E402

_BANNED_RE = re.compile(
    r"\b(as an ai|language model|chatgpt|\bgpt\b|claude|openai|"
    r"i am an ai|generated by|large language model|\bllm\b)\b", re.I)

# Section headers we expect / will render in order. The model returns a JSON
# object keyed by these; we render whatever subset comes back, in this order.
SECTION_ORDER = [
    ("title", None),
    ("overview", "Overview"),
    ("problem", "Problem & Context"),
    ("goals", "Goals & Success Metrics"),
    ("users", "Target Users"),
    ("requirements", "Key Requirements"),
    ("solution", "Solution / Approach"),
    ("outcomes", "Outcomes & Impact"),
]


def load_resume_text() -> str:
    try:
        return RESUME_TXT.read_text()
    except Exception:
        return ""


def load_jd_text(jd_file: Path | None) -> str:
    if not jd_file:
        return ""
    try:
        raw = Path(jd_file).read_text()
    except Exception:
        return ""
    # dryrun JSON plans embed the JD under a few possible keys; fall back to raw.
    try:
        d = json.loads(raw)
        for k in ("jd_text", "job_description", "description", "job_title"):
            if isinstance(d.get(k), str) and len(d[k]) > 40:
                return d[k]
        return d.get("job_title", "") or raw[:4000]
    except Exception:
        return raw[:4000]


def build_prompt(company: str, role: str, jd_text: str, resume_text: str) -> str:
    return f"""You are helping a real product/program manager named Cyrus Shekari
assemble a SANITIZED product brief / PRD to attach to a job application. The
target role is "{role}" at "{company}".

The application form asks: "Please attach a PRD or product brief for a product
you've launched before. Please make sure to redact any sensitive details."

Write a concise, professional one-to-two page PRODUCT BRIEF for a product Cyrus
actually built, drawn STRICTLY from his resume below. The strongest real example
is his Microsoft work where he "Led 0->1 development of an internal Resilience
Automation Platform, defining product requirements and self-service scheduling
capabilities." Build the brief around THAT product (an internal platform that
lets engineering teams schedule, run, and validate large-scale resilience /
recovery drills, replacing a manual 2-person operation with self-service).

HARD RULES:
- Use ONLY facts/metrics that appear in the resume. Do NOT invent customers,
  numbers, dates, or proprietary internal details.
- It is a REDACTED brief: keep it generic enough that no confidential detail is
  exposed. Refer to enterprise customers generically (e.g. "large enterprise
  customers") rather than naming specific accounts.
- Professional PM document tone. No first-person cover-letter语 ("Dear", "I am
  excited"). This is a deliverable artifact, not a letter.
- Do NOT mention this was AI-generated. No meta commentary.

Return ONLY a single JSON object (no markdown fences) with these string keys:
  "title": a short product-brief title (e.g. "Product Brief: Resilience Automation Platform")
  "overview": 2-3 sentence summary of the product and why it exists
  "problem": the problem / context it addressed (manual toil, scale limits)
  "goals": goals and the success metrics used (pull real metrics from resume)
  "users": who the target users were (internal engineering / SRE teams)
  "requirements": 4-6 bullet-style key requirements, separated by newlines, each starting with "- "
  "solution": the approach / how it was built (self-service scheduling, automation, AI agent)
  "outcomes": measurable outcomes & impact (use the real resume metrics)

Resume (source of truth for all facts):
---
{resume_text[:5000]}
---
"""


def call_model(prompt: str, timeout: int = 300) -> str:
    cmd = model_run_cmd(prompt)
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
    if proc.returncode != 0:
        raise RuntimeError(f"model call failed rc={proc.returncode}: {proc.stderr[:400]}")
    out = (proc.stdout or "").strip()
    if not out:
        raise RuntimeError(f"empty model output (rc={proc.returncode}): {proc.stderr[:300]}")
    # model_run_cmd returns the OpenClaw model.run JSON envelope by default:
    #   {"ok":true,...,"model":"claude-...","outputs":[{"text":"<actual>"}]}
    # We must unwrap outputs[0].text; otherwise the envelope (incl. the model
    # name) leaks into parsing and trips the AI-disclosure guard.
    try:
        obj = json.loads(out)
        outs = obj.get("outputs")
        if isinstance(outs, list) and outs:
            t = outs[0].get("text") if isinstance(outs[0], dict) else None
            if isinstance(t, str) and t.strip():
                return t.strip()
        for k in ("text", "output", "content", "result"):
            if isinstance(obj.get(k), str):
                return obj[k].strip()
        if isinstance(obj.get("message"), dict):
            c = obj["message"].get("content")
            if isinstance(c, str):
                return c.strip()
    except Exception:
        pass
    return out


def parse_brief(raw: str) -> dict:
    """Extract the JSON object from the model output (tolerant of fences/prose)."""
    txt = raw.strip()
    # strip code fences
    txt = re.sub(r"^```(?:json)?", "", txt).strip()
    txt = re.sub(r"```$", "", txt).strip()
    # grab the outermost {...}
    m = re.search(r"\{.*\}", txt, re.S)
    if m:
        txt = m.group(0)
    data = json.loads(txt)
    if not isinstance(data, dict):
        raise ValueError("model did not return a JSON object")
    return data


def validate(data: dict) -> list[str]:
    errs = []
    blob = json.dumps(data)
    if _BANNED_RE.search(blob):
        errs.append("AI-disclosure leak")
    if not data.get("overview") and not data.get("solution"):
        errs.append("missing core sections")
    if len(blob) < 300:
        errs.append("too short")
    return errs


def render_pdf(data: dict, company: str, role: str, personal_info: dict,
               out_pdf: Path) -> tuple[Path, Path]:
    from docx import Document  # type: ignore
    from docx.shared import Pt, Inches  # type: ignore

    ident = personal_info.get("identity", {}) or {}
    contact = personal_info.get("contact", {}) or {}
    name = ident.get("full_name") or ident.get("name") or "Cyrus Shekari"
    email = contact.get("email", "")
    phone = contact.get("phone", "")

    doc = Document()
    for section in doc.sections:
        section.top_margin = Inches(0.8)
        section.bottom_margin = Inches(0.8)
        section.left_margin = Inches(1)
        section.right_margin = Inches(1)
    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(11)

    def para(text="", bold=False, size=11, after=6, before=0):
        p = doc.add_paragraph()
        p.paragraph_format.space_after = Pt(after)
        p.paragraph_format.space_before = Pt(before)
        if text:
            r = p.add_run(text)
            r.bold = bold
            r.font.size = Pt(size)
        return p

    title = (data.get("title") or "Product Brief").strip()
    para(title, bold=True, size=15, after=2)
    byline = "  |  ".join([x for x in (name, email, phone) if x])
    if byline:
        para(byline, size=9, after=10)

    for key, heading in SECTION_ORDER:
        if key == "title":
            continue
        val = data.get(key)
        if not val:
            continue
        val = str(val).strip()
        if not val:
            continue
        para(heading, bold=True, size=12, after=2, before=6)
        # requirements (or any newline-bulleted block): render each line
        if "\n" in val:
            for line in [l.strip() for l in val.split("\n") if l.strip()]:
                line = re.sub(r"^[-*•]\s*", "", line)
                bp = doc.add_paragraph(style="List Bullet")
                bp.paragraph_format.space_after = Pt(2)
                bp.add_run(line)
        else:
            para(val, after=6)

    out_pdf.parent.mkdir(parents=True, exist_ok=True)
    docx_path = out_pdf.with_suffix(".docx")
    doc.save(str(docx_path))
    _tr.convert_to_pdf(docx_path, out_pdf)
    return out_pdf, docx_path


def generate(company: str, role: str, *, jd_file: Path | None = None,
             out_pdf: Path | None = None, max_retries: int = 2) -> dict:
    personal_info = json.loads(PERSONAL_INFO.read_text())
    jd_text = load_jd_text(jd_file)
    resume_text = load_resume_text()

    data: dict = {}
    last_errs: list[str] = []
    for attempt in range(max_retries + 1):
        prompt = build_prompt(company, role, jd_text, resume_text)
        if last_errs:
            prompt += ("\n\nYOUR PREVIOUS DRAFT FAILED VALIDATION: "
                       + "; ".join(last_errs) + ". Fix and return valid JSON.")
        raw = call_model(prompt)
        try:
            data = parse_brief(raw)
        except Exception as e:
            last_errs = [f"parse error: {e}"]
            continue
        last_errs = validate(data)
        if not last_errs:
            break
    if last_errs:
        raise RuntimeError(f"product brief failed validation after retries: {last_errs}")

    if out_pdf is None:
        safe = re.sub(r"[^a-z0-9]+", "", company.lower())
        out_pdf = Path("/tmp/openclaw/uploads") / f"Cyrus_Shekari_ProductBrief_{safe}.pdf"
    out_pdf = Path(out_pdf)

    pdf, docx = render_pdf(data, company, role, personal_info, out_pdf)
    return {"pdf": str(pdf), "docx": str(docx), "chars": len(json.dumps(data))}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--company", required=True)
    ap.add_argument("--role", required=True)
    ap.add_argument("--jd-file", default=None)
    ap.add_argument("--out", default=None)
    args = ap.parse_args()
    res = generate(
        args.company, args.role,
        jd_file=Path(args.jd_file) if args.jd_file else None,
        out_pdf=Path(args.out) if args.out else None,
    )
    print(json.dumps(res))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
